### ISSUE TITLE
docs: installation: consider adding eget to the docs

### ISSUE THREAD

**Issue by gfelbing** [stackitcloud/stackit-cli#115]
As there is currently no linux package for the CLI, I use the github release.
I use [eget](https://github.com/zyedidia/eget) to install and manage binaries installed from github.
This could be useful for others as well. I installed it using the following config:

```toml
# ~/.eget.toml
["stackitcloud/stackit-cli"]
asset_filters=["stackit-cli_", "_linux_amd64.tar.gz"]
```

`eget stackitcloud/stackit-cli`
